### ISSUE TITLE
"Quiet" preset

### ISSUE THREAD

**Issue by Squikou** [veista/smartthings#7]
Hi,
I am currently testing the integration in HACS. Really good work.
However, a few things are still missing.
Do you plan to integrate the quiet preset?

![image](https://user-images.githubusercontent.com/87930381/146454265-fbdac326-5912-44f7-9cd1-835b875ab04b.png)

Thanks

**Comment by veista** [comment]
Please see the closed issues.

**Comment by Squikou** [comment]
Ok, I just saw.
I checked and indeed I do not have "quiet" OptionalMode. 
![image](https://user-images.githubusercontent.com/87930381/146512704-d8ff46ef-ee6e-497d-9461-8c781f3ed796.png)

However, the official Smartthings app allows you to manage it through my phone. Why this difference?

**Comment by veista** [comment]
Did you try the resolution of the issue: recycle the power on your AC?

**Comment by veista** [comment]
> However, the official Smartthings app allows you to manage it through my phone. Why this difference?

The st app is closed source, so I do not know. It is either hard coded or it uses OCF. OCF functions are only available through the execute interface and this makes it hard to implement OCF functions. That is why the display light is the only OCF function I have implemented. (Most meaningfull functions are available through the ST API). Did this anwser your question?

Also if you like the integration, please star the repo, this helps me out a ton. Thanks.

**Comment by Squikou** [comment]
> Did you try the resolution of the issue: recycle the power on your AC?

Unfortunately, still the same behavior even after recycling the power.

**Comment by veista** [comment]
Ok. I can send you a hard coded version. You will have to replace/edit climate.py every time there is an update. 

There is little I can do to this at this point. One option is that I hard code the modes for your model. Can you send me a full sheet of capabilities from the st ide, so I can try to implement this.

**Comment by veista** [comment]
Replace this in your climate.py

    @property
    def preset_modes(self):
        """Return the list of available ac optional modes, in samsung case check that windfree cannot be selected when in heating."""
        restricted_values = ["windFree"]

        supported_ac_optional_modes = [
            "off",
            "sleep",
            "speed",
            "quiet",
            "windFree",
            "windFreeSleep",
        ]

        if (self._device.status.air_conditioner_mode == "auto") or (
            self._device.status.air_conditioner_mode == "heat"
        ):
            if any(
                restrictedvalue in supported_ac_optional_modes
                for restrictedvalue in restricted_values
            ):
                reduced_supported_optional_modes = supported_ac_optional_modes
                reduced_supported_optional_modes.remove("windFree")
                return reduced_supported_optional_modes
        else:
            return supported_ac_optional_modes

**Comment by veista** [comment]
Have you tried restarting the AC from the breaker (Power cycle the AC)?

**Comment by dimmuboy** [comment]
I tried it because I have same issue but it doesn't work.
When I replace code it shows _quiet_ preset but when set it change nothing in SmartThins app.

This is state when I change _quiet_ in app with original code
![image](https://user-images.githubusercontent.com/12607479/148696557-fea250ee-a989-4217-bc06-4c74a00d81e3.png)
and this after code change
![image](https://user-images.githubusercontent.com/12607479/148696852-253c0f03-57b1-4aef-845c-d501b7823cdb.png)

**Comment by veista** [comment]
It might be that your AC does not support quiet mode through the ST API. This is really weird that these work so differently to other models.

What you can do is cURL the AC for me. That is the only way I can help you. 

Do you both have the same model AR07TXFCAWKN?

**Comment by veista** [comment]
Does your ac beep if you have volume on and toggle off preset and then to quiet?

**Comment by veista** [comment]
Also does you log show any error when you try selecting quiet mode? Also please note that you cannot select any mode if it is already selected.

**Comment by dimmuboy** [comment]
Mine is AR12TXCAAWKNEU but visually is very similar.
There is no sound feedback after change preset to quiet (any other make a beep).
Can you share curl query with us to test please?

**Comment by veista** [comment]
Be sure you have volume or beep turned on when trying. It should beep when it does something if you have beep/volume/sound on.

1. curl -X GET 'https://api.smartthings.com/v1/devices?content=all' -H 'Authorization: Bearer <api_token>'

make note of your deviceId of which device you want to query

2. curl -X GET 'https://api.smartthings.com/v1/devices/<INSERT THE deviceId HERE>/status' -H 'Authorization: Bearer <api_token>'

Replace <INSERT THE deviceId HERE> with the deviceId

Replace <api_token> with your api token.

If you are willing to debug this with me you should download and install postman https://www.postman.com/ It is more convenient than cURL.

**Comment by Squikou** [comment]
> Be sure you have volume or beep turned on when trying. It should beep when it does something if you have beep/volume/sound on.
> 
>     1. curl -X GET 'https://api.smartthings.com/v1/devices?content=all' -H 'Authorization: Bearer <api_token>'
> 
> 
> make note of your deviceId of which device you want to query
> 
>     2. curl -X GET 'https://api.smartthings.com/v1/devices/<INSERT_THE_deviceId_HERE>/status' -H 'Authorization: Bearer <api_token>'
> 
> 
> Replace <INSERT_THE_deviceId_HERE> with the deviceId
> 
> Replace <api_token> with your api token.
> 
> If you are willing to debug this with me you should download and install postman https://www.postman.com/ It is more convenient than cURL.

I just tried the curl command above and I don't get any sound.

You will find the return of the curl script attached.

[curl-log-17-01-2022.txt](https://github.com/veista/smartthings/files/7884347/curl-log-17-01-2022.txt)

**Comment by veista** [comment]
Please try the latest release.

**Comment by Squikou** [comment]
Works perfectly ! Nice works, thanks.

**Comment by mjeshurun** [comment]
Hi @veista , thank you for your work creating and supporting the Samsung AC integration 🙏

I also have two Samsung Windfree AC's with the Quiet preset availale to use with the IR remote and the SmartThings app, but your HA climate integration doesn't show the Quiet mode as an option for both AC's.

I tried to power recycle my AC's, but the Quiet option is still not showing. 

I also can't see Quiet as a listed option in the SamrtThings Advanced website, although the IR remote and the SmartThings app are able to set the AC's to work in Quiet mode.

Another function I can't see in the HA climate integration is a way to enable/disable the LED display of these AC's.

Can I please ask for your assistance?

**Comment by mjeshurun** [comment]
Hi @Squikou , 
Do you think you could help me solve my issue? 
I also can't see the Quiet preset in HA for my Windfree AC's, but I can set it on both AC's using the IR remote and the official Smartthing ios app.
